### ISSUE TITLE
Forking back to original code

### ISSUE THREAD

**Issue by blankdots** [EGA-archive/beacon-2.x#14]
This is more of a request rather than an issue, and I am a bit unsure how to bring it up.

Noticed that some of the code (mainly the one at: https://github.com/EGA-archive/beacon-2.x/tree/master/src/beacon_api) is similar and in some cases identical to the one we developed at https://github.com/CSCfi/beacon-python .
We feel honoured to be the source for that project, but we do have a request  if it would it be possible to have the link back to original repo as a fork.

The main reasons are that we would like to get changes from this 2.x version, and at the same time we would like to contribute back (we noticed some issues that we have patched in our repository).
Not sure how this would affect this repo's structure (e.g. splitting the beacon from the ui) but it would be nice to track the change easier.

I think this fork-ing model in place will stream line the collaboration a bit better, also it would give credit to original developers and to other contributors that we had for NBIS and DDBJ on that repository.

Thank you.

**Comment by silverdaz** [comment]
We will gladly give you the necessary acknowledgments. There is no doubt on that.

I suggest we include a section in the README.md file, visible then on the "front page".

However, I'm afraid that forking the repo from CSCfi is not a possibility, for several reasons:
* We have grouped some other components inside our repo (like the UI, our own tests)
* We have diverged substantially from the original code. At first, it's true that we only added the Beacon 2.0 features, but now, we have refactored the code and there are too many differences.
* Finally, as this repo is supposed to be the reference implementation, it makes more sense to "link" in the other direction. Well, so I've been told.

That said, we greatly appreciate the effort and will gladly give you the credits you deserve.
Let me know if you have a better idea.

**Comment by blankdots** [comment]
thank you for your response.
Acknowledgements are fine, please add them, we will link back to this repo as well but in readme, as we would like to take the source code in a different direction with some fancy new bells and whistles 

It would have been nicer if we could collaborate on the code, but it seems we will have to rely on specification, if forking to original repo is not possible :slightly_frowning_face: 

Overall I think it will be valuable to have multiple implementations of the same specification, but in hindsight it would have been beneficial to fork even though one diverges from original code base, that how it usually goes not linking back :slightly_smiling_face:  .

**Comment by blankdots** [comment]
Feel free to close once the link has been put in `README.md`

**Comment by silverdaz** [comment]
Closing as solved in PR #30
