### ISSUE TITLE
Use only one field for all the requested schemas

### ISSUE THREAD

**Issue by sdelatorrep** [EGA-archive/beacon-2.x#26]
Instead of having one requested schema field for each object (e.g. `requestedSchemaVariant`), use only one field as we know to which object applies each schema.
Also, be careful when querying variants. We have 2 schemas in place: `Variant` and `VariantAnnotation`. In this case, the unified field must accept 2 values (although, probably nobody will request anything like this `requestedSchemas=beacon-variant-v2.0.0-draft.2,ga4gh-phenopacket-variant-annotation-v1.0`, technically it's possible).

**Comment by silverdaz** [comment]
Closing as solved by #30
