### ISSUE TITLE
Document Authentication for Beacon

### ISSUE THREAD

**Issue by amanjeev** [EGA-archive/beacon-2.x#8]
### Description
Trying to see if I can add beacon successfully behind our authentication server.

### Proposed solution
A section in README.md would be great.

### Definition of Done
Authentication is document.

**Comment by silverdaz** [comment]
The beacon UI already supports AAI.
However, you are only mentioning the _authentication_ part, and not the _authorization_. The authentication is already factored in. The authorization though is _outside_ beacon.
You need a permission server that would tell you if a given user has access to the given resource.

**Comment by amanjeev** [comment]
Thanks @silverdaz ! I have been able to move Beacon behind our API Gateway. I believe that is what you want people to do. Am I right?

I am closing this for now.
